### ISSUE TITLE
Quoted wrong source?

### ISSUE THREAD

**Issue by HUANG0421** [readchina/ReadAct#229]
I read the text from Zhang Yang (1999), but I didn't find the contents about Du Fu, Du Pengcheng and them works (based on the Excel Document, line 110-112). According to the records, the names of these 2 persons and the works are all quoted in the Zhang's Book.

Maybe it would be a wrong source? Or could it be reviewed? Thank you. :-)

**Comment by duncdrum** [comment]
I do not know @LenaHenningsen any thoughts?

**Comment by LenaHenningsen** [comment]
Sorry for the incomplete data:
l. 111: Zhang Yang stiches the two quotations on his towel while imprisoned (the quotation is: 莫自使眼枯，收汝泪纵横；眼枯即见骨，天地终无情！) (source: Zhang 1999, 206) so: new act type, I guess: sticking on a towel
The second is a poem by Li Qingzhao: "生当作人杰，死亦为鬼雄。至今思项羽，不肯过江东！" (source Zhang 1999: 207)
Du Pengcheng is a wrong entry by me as it does not refer to a reading act.

**Comment by duncdrum** [comment]
@mira-gruenwald when you have time can you check the entries and wrap this up please, thank you.
