### ISSUE TITLE
Romm and Rommel - Publication info

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#247]
Hi, 
could someone help me to find information about the following entries:

- [x] PS0352  
战时日记 by Erwin Rommel. I'm not sure if [The Rommel Papers](https://en.wikipedia.org/wiki/The_Rommel_Papers) is the right English version.

- [ ] [AW00100](https://www.imdb.com/title/tt0029132/)
- [ ] [AW00101](https://www.imdb.com/title/tt0031564/)

Two movies by Mikhail Romm which are missing the date of release in China.

**Comment by duncdrum** [comment]
What makes you doubt *The Rommel Papers*? Seems feasible to me. 
As for the movies, are you just in doubt when they came to China, or if these are the ones?

**Comment by duncdrum** [comment]
@mira-gruenwald good to close?

**Comment by mira-gruenwald** [comment]
Thank you!
Yes, I couldn't find out when the movies came to China, so I left a gap in the ArtWork file.
