### ISSUE TITLE
Multiple authors?

### ISSUE THREAD

**Issue by damianodamiani** [readchina/ReadAct#342]
See row 361 in the old Excel file: the Gotha Program was written by Babel, Libknecht and Hasenclever but thus far we always had one author only. How do we deal with it? Using SAPD as an author could be a way out (like Mira did in the Excel file), but then what about all the fields like Sex, Birth Year, etc.?

**Comment by duncdrum** [comment]
groups of authors are an institution,  if there is no widely used name for the institution you are free to name them by your self.
see #237
