### ISSUE TITLE
Does this mean 'Rustication'?

### ISSUE THREAD

**Issue by ed-shred** [readchina/ReadAct#377]
This bio contains the sentence '1976年高中毕业曾在四川金堂县插队一年半。' Is this a way of saying 'rustication'? (https://baike.baidu.com/item/%E7%8E%8B%E8%BE%89%E8%80%80)

**Comment by damianodamiani** [comment]
my dictionary says 'chadui: to live in a rural community during Cultural Revolution' so seems like rustication to me, what do you think @LenaHenningsen ?

**Comment by LenaHenningsen** [comment]
Sorry, this escaped me – and yes, I think that works.

 

Von: Damian <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Dienstag, 28. Mai 2019 um 16:20
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Does this mean 'Rustication'? (#377)

 

my dictionary says 'chadui: to live in a rural community during Cultural Revolution' so seems like rustication to me, what do you think @LenaHenningsen ?
