### ISSUE TITLE
Anne Frank P0335

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#394]
I think she deserves an issue of her own. According to the several texts by some authors chart, there are references to 3 different texts by her; but the primary source table has (as can be expected) only one...

**Comment by duncdrum** [comment]
OK the second work by A. Frank is from `A00692` which refers to `PS00308` which doesn't exist, the code therefore attributed it to the author of `PS00307` which is her *Diary*

See #299

**Comment by duncdrum** [comment]
see #399

**Comment by duncdrum** [comment]
closed by #498
