### ISSUE TITLE
Emily Bronte again...

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#397]
Currently Emily Bronte P0321 has 4+1 reading acts (i.e. 5 reading acts referring to 2 titles), but there is only Wuthering Heights in the primary sources...

**Comment by duncdrum** [comment]
This is not a bug, the second book is an unknown title by Bronte in act `A00293`

**Comment by LenaHenningsen** [comment]
Thanks much! 

 

Von: Duncan Paterson <notifications@github.com>
Antworten an: readchina/ReadingData <reply@reply.github.com>
Datum: Dienstag, 20. August 2019 um 14:55
An: readchina/ReadingData <ReadingData@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Author <author@noreply.github.com>
Betreff: Re: [readchina/ReadingData] Emily Bronte again... (#397)

 

This is not a bug, the second book is an unknown title by Bronte in act A00293

**Comment by duncdrum** [comment]
Unless her poems also circulated at the time, in this instance though we could declare that the book in question must have been *Wuthering Heights*. But thats us, not whats in the sources.

**Comment by duncdrum** [comment]
see #399
