### ISSUE TITLE
Acts 716, 717, 1025

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#405]
I am going through Reading Acts referring to How the Steel was Tempered PS00218 and The Gadfly PS00194, and could not find the references in the secondary sources that are in the database.
This holds true for Acts 716, 717, 1025, 1027 (Xu Haoyan's text has nothing to do with How the Steel...)

For A01026 maybe change Act TYPE TO AT16, and modify comment: 
Huang Xiaolong realizes that the Pavel Korchagin ideal and 保尔·柯察金式的人生理想和追求 was the source for many mistakes and can now explain his disillusionment. (the year 1971 seems correct).

For A00715 add as comment: Zhang Yang refers to this is a childhood reading (age 8)
Same comment also for A00412

**Comment by duncdrum** [comment]
acts: 716, 717, 1025, 1027 are all created and last edited by @mira-gruenwald maybe you have an idea?

@HUANG0421 act review is one of the nexts steps i believe.

**Comment by duncdrum** [comment]
@LenaHenningsen i m afraid i don't understand the issue with `716, 717, 1025, 1027` what is the problem with these?

**Comment by LenaHenningsen** [comment]
I doublechecked : 716, 717 and I think 1025 should be fine. But 1027 is wrong. The entire text by Xu Haoyan, as far as I can tell, has no reference to How the Steal was Tempered. So I'd suggest deleting the entire act.

**Comment by LenaHenningsen** [comment]
(But as I wrote earlier, deleting seems not to work currently. Sorry.)
