### ISSUE TITLE
Mao Zedong (again...)

### ISSUE THREAD

**Issue by LenaHenningsen** [readchina/ReadAct#406]
I probably made a mistake, but maybe you can clarify... In order to have a deeper look at our friend the chairman, I went through the entries for P0174. In the PS chart, I somehow only found entries to 13 titles by him. At least two of these (PS00470 and 471) have no reading act ascribed to them. How can we then have 23 different titles in the lovely chart we made? 
Thanks much!

**Comment by duncdrum** [comment]
first guess quotations (which are now in the act chart)?

**Comment by duncdrum** [comment]
Quotations indeed
