### ISSUE TITLE
Zheng Yi - Red Maple

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#438]
There is a reading act related to a quotation from Mao:

"Der Vorsitzende Mao sagt: Wenn wir erst einmal die schwierige Etappe des bewaffneten Kampfes hinter uns haben, liegt eine ebene Wegstrecke vor uns." (SS00606, P. 37)

@LenaHenningsen 
I was looking for an English translation, but couldn't find that quotation in _Quotations From Chairman Mao Tse-tung_.
Maybe there is another source for it? Or could it be that this is a fictional quotation?

**Comment by damianodamiani** [comment]
Hey, it's a (half-)quote from Mao's 1938 _On Protracted War_ where he writes:

> 跨过战争的艰难路程之后，胜利的坦途就到来了，这是战争的自然逻辑 (https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193805b.htm)

which translated fast would be something like "After crossing the difficult path of war, the plain road to victory has arrived—that is the natural logic of war."

The official translation was thus:

> After travelling the hard stretch of road we shall reach the highway to victory. This is the natural logic of the war. (http://www.mzdbl.com.cn/maoxuan/maoxuan2-e/mswv2_09.htm)

**Comment by LenaHenningsen** [comment]
DANKE!

 

Von: Damian <notifications@github.com>
Antworten an: readchina/ReadAct <reply@reply.github.com>
Datum: Freitag, 25. September 2020 um 17:41
An: readchina/ReadAct <ReadAct@noreply.github.com>
Cc: LenaHenningsen <Lena.Henningsen@sinologie.uni-freiburg.de>, Mention <mention@noreply.github.com>
Betreff: Re: [readchina/ReadAct] Zheng Yi - Red Maple (#438)

 

Hey, it's a (half-)quote from Mao's 1938 On Protracted War where he writes:

跨过战争的艰难路程之后，胜利的坦途就到来了，这是战争的自然逻辑 (https://www.marxists.org/chinese/maozedong/marxist.org-chinese-mao-193805b.htm)

which translated fast would be something like "After crossing the difficult path of war, the plain road to victory has arrived—that is the natural logic of war."

The official translation was thus:

After travelling the hard stretch of road we shall reach the highway to victory. This is the natural logic of the war. (http://www.mzdbl.com.cn/maoxuan/maoxuan2-e/mswv2_09.htm)

**Comment by duncdrum** [comment]
closed by #498
