### ISSUE TITLE
[act]: site of reading

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadAct#441]
The discussion entries on `Act` often contain information about the the site / location / place of a reading act, yet we are missing a data field to capture them. 
We capture spatial information about persons, but not about acts. We should. There are two ways to generate this quickly, unfortunately none are automatable. 

1.  read the discussion entries and extract site information where it is hidden in there. 
1.  cross reference the information based on the date of the reading with biographical info about where the subject were according to the info on `Persons.csv`

**Comment by duncdrum** [comment]
@whalekeykeeper this one is for mira i think

**Comment by mira-gruenwald** [comment]
Hey @duncdrum @whalekeykeeper 
What if the site info is not about the reading act itself, but about the location where someone accessed a work? (A00760 / A00763)
Do we add a new act entry?
There is "to find" as an act type. So maybe a more general act type, like "to access" would be an option?

**Comment by duncdrum** [comment]
i'd say that kind of information fits very well as the `site` of the existing `to find` action, so no new type necessary just another action entry in `Acts`. In cases of doubt where there are location data points hidden in the discussion prose simply adding the ID: 
| discussion |
|--|
| She dreamt of Paris (SP123123) | 

would be very helpful.

If you add new `to find` actions please make sure that they are not duplicates.
