### ISSUE TITLE
Rustication Cai Xiang 蔡 翔

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#446]
Cai Xiang 蔡 翔 (AG0191) was rusticated in Guzhen. The end date in the rustication table is probably wrong.
@whalekeykeeper could you help me find the right end date of his rustication? Thanks a lot!

https://baike.baidu.com/item/%E8%94%A1%E7%BF%94/3300403

**Comment by whalekeykeeper** [comment]
Sure. Would love to.
According to searching, he went back to Shanghai in 1974. The accurate date is unknown.
Here are references:
1. "您1970年赴安徽插队务农，1974年回上海进铸件厂做工人，1978年考入大学“， http://www.aisixiang.com/data/110969.html
2. “1970年赴安徽固镇插队，1974年任上海三轮铸件厂工人”， http://www.chinawriter.com.cn/n1/2016/0627/c404930-28488041.html
3. “1976年10月的一个下午……那一年，我从农村回到城市已有两年，在一家工厂做工“，https://www.jintian.net/today/?action-viewnews-itemid-2365

**Comment by mira-gruenwald** [comment]
Thank you  :)
