### ISSUE TITLE
update dependencies on CI

### ISSUE THREAD

**Issue by duncdrum** [readchina/ReadAct#447]
goodtables is now frictionless
bump travis to more recent VM
update python version
update basex (if i can find out how on CI)

problem https://github.com/frictionlessdata/frictionless-py/issues/614

**Comment by duncdrum** [comment]
progress but we are now hitting https://github.com/frictionlessdata/frictionless-py/issues/609 a fix has been merged so we have to wait for the next release of the frictionless package (probably `4.0.0`).

**Comment by duncdrum** [comment]
ok the stable release is out we're now at v4 🎉 

@whalekeykeeper would you like to take a stab at fixing the outstanding validation issues revealed by the latest run on Travis?

**Comment by whalekeykeeper** [comment]
> ok the stable release is out we're now at v4 🎉
> 
> @whalekeykeeper would you like to take a stab at fixing the outstanding validation issues revealed by the latest run on Travis?

I tried to run the command locally and got an error message:
`schema-error  The data source could not be successfully described by the invalid Table Schema: constraint "max-length" is not supported by type "any"`
But I do not know which file to look at for this error.

**Comment by duncdrum** [comment]
yup thats the same error as on travis. if you want you can open an issue with them about the missing location in the log. For now you ll have to search and find the instances manually `⌘F` ftw

**Comment by duncdrum** [comment]
```json
"name": "act_id",
      "description": "A and a five-digit number (leading zeros)",
      "constraints": {
        "required": true,
        "unique": true,
        "max-length": 6,
        "pattern": "A[0-9]{5}"
```

https://github.com/readchina/ReadAct/blob/master/csv/schema/Act.json#L2-L10

does not define a `type` so it is treated as type `any`. It wants us to define a `type` here that supports the constraints we want to place on the contents. We should however check, based on past experiences, if this is actually necessary. Aka see where in the specs does it say that `any` cannot have `max-length`. If it can have `max-length` there is a bug in the validator, if it can't we need to pick and declare a new type.

**Comment by whalekeykeeper** [comment]
Tried with replace "max-length" with "maxLength", "min-length" with "minLength" according to the documentation of constraint properties, still, similar error messages were returned.

An issue is opened #https://github.com/frictionlessdata/specs/issues/719
