### ISSUE TITLE
Reading Time in Zheng Wenguang 郑文光 1981: “Star Camp” 星星营

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#457]
Hello @LenaHenningsen,

I'm not sure about the reading time and (narrative) age of the protagonists in Star Camp. You mentioned the CR in your notes, would this be the reading time?

Thanks a lot!

**Comment by LenaHenningsen** [comment]
Yes, I would put CR for reading time (in the case of Wang, the RA would be refer to and that is the activity that takes place during the CR). 

About the age of the uncle: I think that was not specified; he is a grown-up… and so is the guy who later on quotes from The White Haired Lady

 

Thanks much!

 

Von: Mira Grünwald ***@***.***>
Antworten an: readchina/ReadAct ***@***.***>
Datum: Donnerstag, 25. März 2021 um 07:21
An: readchina/ReadAct ***@***.***>
Cc: LenaHenningsen ***@***.***>, Mention ***@***.***>
Betreff: [readchina/ReadAct] Reading Time in Zheng Wenguang 郑文光 1981: “Star Camp” 星星营 (#457)

 

Hello @LenaHenningsen,

I'm not sure about the reading time and (narrative) age of the protagonists in Star Camp. You mentioned the CR in your notes, would this be the reading time?

Thanks a lot!

**Comment by duncdrum** [comment]
closed by #498
