### ISSUE TITLE
Reading time - Science Fiction

### ISSUE THREAD

**Issue by mira-gruenwald** [readchina/ReadAct#458]
Hi @LenaHenningsen ,

could you help me with the following titles? I don't know the reading time in:

The Secret of The ‚Venus People‘

Paradise Lost

G is for Goddess

Elephants With Their Trunks Removed

Thank you very much! :)

**Comment by LenaHenningsen** [comment]
Reading time is really difficult - as we have stories set in a future setting, measured from the time when the stories are written. The thing is, it does not make so much sense to put a "year" here: the important thing might be that the reading time might be 20 or 30 years ahead from when the readers first got the book. So this really is tricky...

The Secret of The ‚Venus People‘  >>> this broad reference to science fiction is early in the plot before he goes on his mission...

Paradise Lost >>> I think that one only has intertextual references, no explicit reading acts. 

G is for Goddess >>> reading time is early in the narrative when the protagonist is studying.

Elephants With Their Trunks Removed >>>. the text is 1958, these stories tend to be set in a mid-term future, something like 20-40years ahead, I guess. The geography book is "read" early in the plot.

Hope that helps a bit...

**Comment by duncdrum** [comment]
I think we should aim to at least guess the century of the reading time in sci-fi plots.

**Comment by LenaHenningsen** [comment]
That is an option - or/alternatively something like narrative past / present / future

**Comment by mira-gruenwald** [comment]
hey @duncdrum @LenaHenningsen
I'm still wondering how to handle reading time. In most cases, as you mentioned, the story takes place in a future setting. If no exact year was given, I estimated the year (i.e. 2030..2050~) as discussed before.
But we don't know the exact dates. Do you think it is reasonable to proceed this way? And how to deal with intertextual references since these are not explicit reading acts?

**Comment by LenaHenningsen** [comment]
The longer I think about it: for the stories from the Maoist time, it is a convention that the stories are set about one generation. (And probably also the texts from the immediate post-Mao time).
For the more recent text which are most of the texts in the sample, I think they tend to be less clear on that. I would prefer to have something like "narrative future" (not really good) as a marker. Here, the FICTIONAL aspect is more important than being specific...

**Comment by duncdrum** [comment]
I think that best effort approximations here are important and the way to go. The narrative time scale of sci-fi plots is meaningful, and we can often say more then just `future`. 

Generations are a good indicator for rough time scale, if there are no explicit clues that’s interesting in an of itself. I trust Mira to make a good call. Pick a starting point your comfortable with. The fact that this a factionalized projections is already captured by the data structure, so whatever we can say about dates we should say. Where it’s maximally underspecified, pick a convention. More then 1 generation, so 70years after writing +x.

**Comment by LenaHenningsen** [comment]
Well, I trust Mira on everything, more than myself. And a number of the texts don't have clues. Or I was too dumb to get them ;)
