### ISSUE TITLE
Open new repository WikidataLookUp  that shares a namespace with ReadAct

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#470]
Task:
To create a new repository WikidataLookUp that shares a namespace with ReadAct;
this new repository should contain all the scripts for authenticity verification/validation;
all the Person, Space, Institution should be cross-referenced with the Wikidata database;
test cases should be added for scripts;
GitHub Action should be set up for this new repo.

Estimated finish time: this week (until 30th July)

**Comment by whalekeykeeper** [comment]
@duncdrum Hi Duncan, I have checked up for "git namespace", but the documentation isn't really helpful and I didn't find a good tutorial. Could you give me a hint about setting this repo up?

**Comment by duncdrum** [comment]
1. Go to the [org's dahsboard](https://github.com/orgs/readchina/dashboard)
2.  Click new 
![Screenshot 2021-07-26 at 13 33 23](https://user-images.githubusercontent.com/6205362/126982597-253b6d92-f440-4fbe-ae5d-bacf9694c969.png)
3. Make sure that the owner of the repo is `READCHINA`
![Screenshot 2021-07-26 at 13 34 32](https://user-images.githubusercontent.com/6205362/126982635-695ac705-9bb9-4d71-99d8-7de29f9cc011.png)
4. follow prompts and fill out forms.

**Comment by whalekeykeeper** [comment]
> 1. Go to the [org's dahsboard](https://github.com/orgs/readchina/dashboard)
> 2. Click new
>    ![Screenshot 2021-07-26 at 13 33 23](https://user-images.githubusercontent.com/6205362/126982597-253b6d92-f440-4fbe-ae5d-bacf9694c969.png)
> 3. Make sure that the owner of the repo is `READCHINA`
>    ![Screenshot 2021-07-26 at 13 34 32](https://user-images.githubusercontent.com/6205362/126982635-695ac705-9bb9-4d71-99d8-7de29f9cc011.png)
> 4. follow prompts and fill out forms.

My mistake. I was looking for methods like `git clone ext::'git --namespace=foo %s /tmp/prefixed.git'` and for the repository ReadAct.
Thank you a lot.
