### ISSUE TITLE
Inconsistent person id AG0626 and AG1000

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#491]
In `Person.csv`, the last two `person_id` are: `AG0626` and `AG1000`.
For appending more person entities into this CSV table in the future, one question is: should the next one starts with `AG0627` and so on with paying attention to skip `AG1000`, or eliminate this inconsistence before integrating the automatic person generation?

**Comment by whalekeykeeper** [comment]
@duncdrum I will use `AG1001` as the start for now. It is easy to modify in the future if needed.

**Comment by duncdrum** [comment]
yes `AG1001` is good, we will always have to account for ID ranges to be reserved, so them not being natural number sequences is not an issue.

**Comment by duncdrum** [comment]
closed by #498
