### ISSUE TITLE
space_type for items SP0447 and SP0448 in Space.csv

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#496]
Should the following two entries have `space_type` `PL` since they have latitude and longitude values?

space_id | old_id | space_name | space_type | name_lang | lat | long | note | created | created_by | last_modified | last_modified_by
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SP0447 |   | Tian'anmen Square | L | en | 39.9042 | 116.407396 |   | 2021-01-05 | MG | 2021-01-05 | MG
SP0448 |   | Three Gorges Dam | L | en | 30.813290 | 111.014292 |   | 2021-01-05 | MG | 2021-01-12 | MG

**Comment by duncdrum** [comment]
Place and location aren’t distinct classes in the strict sense. There can be overlap, in which case first entry into readact determines the type. Which is what happened in those examples.

**Comment by whalekeykeeper** [comment]
> Place and location aren’t distinct classes in the strict sense. There can be overlap, in which case first entry into readact determines the type. Which is what happened in those examples.

which is to say, an entry with `space_type` `L` might have `lat` and `long`, but also might not have?

**Comment by duncdrum** [comment]
exactly

**Comment by duncdrum** [comment]
@whalekeykeeper good to close ?

**Comment by whalekeykeeper** [comment]
> @whalekeykeeper good to close ?

yes
