### ISSUE TITLE
Add wikidata id to Agent table

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#509]
References: Person.csv Institution.csv

**Comment by duncdrum** [comment]
@whalekeykeeper your agent table in the `add-wikidata_id` branch has been truncated. The table should have 950 rows, but there are only 659 in that branch. From what i can see a lot of Institutions are missing, and a whole bunch of fictional entities have been lost. I ll open a separate PR trying to clean this up.
