### ISSUE TITLE
Redundant space_name in Space.csv

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#516]
Redundant `space_id` in ReadAct, for example:

space_id | old_id | space_type | space_name | language | lat | long | wikidata_id | note | created | created_by | last_modified | last_modified_by
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SP0262 | PL0275 | PL | Guilin | en | 25.234479 | 110.179953 | Q189633 |   | 2018-06-11 | MG | 2022-06-29 | ReadActor
SP0298 | PL0311 | PL | Guilin | en | 25.2344 | 110.1799 | Q189633 |   | 2018-06-01 | DM | 2022-06-29 | ReadActor

These data are influencing the behavior of ReadActor while mapping `space_id` with `space_name` and the way of mapping them back.

**Comment by duncdrum** [comment]
i ll fix this in the `2.0RC` branch should be a simple search and replace
