### ISSUE TITLE
Fictionality of agents

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/ReadAct#517]
According to the latest update of the agent table, a new column `fictionality` is now used to mark if the agent is fictional or not.

I have two observations.

First: 
On one hand, Q-ids we found for these fictional agents might be wrong if they are not in Wikidata but a person has the same name is in Wikidata. For example, [`Wang Miao`](https://www.wikidata.org/wiki/Q94637197) is not `AG0713`, a fictional figure in "The Three-Body Problem", but an author [`王苗`](http://lod.nl.go.kr/page/KAC201000231). On the other hand, famous fictional figures are possible to be existing in Wikidata database. It is difficult to evaluate the success rate.

Second: 
Agents like `AG0673`(刘心武), `AG0696`(Heinrich Heine) are marked as `F`. Plus some agents have their names in traditional Chinese like `AG0722 `(劉), agents like "AG0707"(本名为让-巴蒂斯特) and `AG0748`(尼古拉耶娃著) have mistakes in their name.

**Comment by duncdrum** [comment]
About the false match for Wang Miao, that’s just a risk we have to live with. 

Fictional characters like Harry Potter will likely get the right qid. 

The fictionality of an agent is tied to the reading acts they perform. It’s impossible to derive from an external source. 

As for misspelling in names that’s something readactor can correct like any other false datum. 

We should check with Lena about this entries though.

**Comment by whalekeykeeper** [comment]
> About the false match for Wang Miao, that’s just a risk we have to live with.
> 
> Fictional characters like Harry Potter will likely get the right qid.
> 
> The fictionality of an agent is tied to the reading acts they perform. It’s impossible to derive from an external source.
> 
> As for misspelling in names that’s something readactor can correct like any other false datum.
> 
> We should check with Lena about this entries though.
Thanks for reply.
Understanable.
Plus, ReadActor won't correct names for now but this is something easy to modify when necessary.

**Comment by LenaHenningsen** [comment]
Hi everyone, Heinrich Heine and Liu Xinwu are not fictional. I think of Heinrich Heine, someone may quote a text by him in a fictional text, but he never appears as a fictional Heinrich Heine agent in the sources. Do you need responses on AG0707"(本名为让-巴蒂斯特) and AG0748(尼古拉耶娃著), too?
